'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LobbyClient.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _Error() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_Error", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Admin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Admin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AFK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AFK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AFK_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AFK_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ask2Join() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ask2Join", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Blocked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Blocked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BlueCheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlueCheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Captain() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Captain", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cheater() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cheater", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cheater_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cheater_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cheater_remove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cheater_remove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property client() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("client", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property donator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("donator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eeaoc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eeaoc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eeboth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eeboth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Firewall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Firewall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Flashlight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flashlight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FriendJoined() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("FriendJoined", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property FriendLeft() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("FriendLeft", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property friends() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("friends", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property friends_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("friends_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property friends_offline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("friends_offline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property friends_remove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("friends_remove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GameClosed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GameClosed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GameOpen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GameOpen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ignore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ignore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ignore_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ignore_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ignored() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ignored", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Invited() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Invited", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property InviteNot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InviteNot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Joystick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Joystick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property locate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("locate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Moderator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Moderator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Muted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Muted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Password() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Password", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SkillAdvanced() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SkillAdvanced", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SkillExpert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SkillExpert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SkillIntermediate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SkillIntermediate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SkillNovice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SkillNovice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tombstone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tombstone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property update() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("update", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property whisper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("whisper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WhisperRecv() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("WhisperRecv", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
